github.com:
    user: b00y0h
    oauth_token: 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
    git_protocol: ssh
    users:
        b00y0h:
            oauth_token: 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
