format = """
$username\
$hostname\
$directory\
$cmd_duration\
$line_break\
$node\
$character"""

right_format = """
$git_branch\
$git_state\
$git_status\
$battery\
$time\
"""
# A continuation prompt that displays two filled in arrows
continuation_prompt = "▶▶"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
symbol = " "
style = "bright-blue"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
# conflicted = " "
# untracked = " "
# modified = " "
# staged = " "
# renamed = " "
# deleted = " "
# stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-green"

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'
style = "yellow"

# Displays current directory.
[directory]
format = "[$path]($style) "
style = "blue"
truncate_to_repo = true
truncation_length = 3 # parent directories to show; default is 3
truncation_symbol = "…/"